<!--
%\VignetteEngine{tinymarkdown::mdweave_to_html}
%\VignetteIndexEntry{Using tinymarkdown as a vignette engine}
-->
---
title: Using tinymarkdown as a vignette engine
author: Jan van der Laan
css: "dark.min.css"
---



To use tinymarkdown as an engine for your package vignettes you will need to do the following:

1. Specify tinymarkdown as your vignette builder in your `DESCRIPTION` file:

```
VignetteBuilder: tinymarkdown
```

2. Add tinymarkdown as a dependency of your package. If your package doesn't use tinymarkdown otherwise
you can add it to your `Suggests` field in the `DESCRIPTION` file:

```
Suggests: 
    tinymarkdown
```

4. Use the extension `.Rmd` for your vignette.

3. Specify the vignette engine in your vignette. You have to add the following line to your vignette:

```
%\VignetteEngine{tinymarkdown::mdweave_to_html}
```

Instead of `mdweave_to_html` you can also use `mdweave_to_pdf` to generate a vignette in PDF format. 
It is easiest to do that in a comment section in your markdown file. For example, start your 
markdown file with:

```
<!--
%\VignetteEngine{tinymarkdown::mdweave_to_html}
%\VignetteIndexEntry{The title of the vignette}
---
title: The title of the vignette
---
...
-->
```


## Custom styling

By default the default templates and styling of the pandoc installation on your machine 
will be used. 
